### ISSUE TITLE
docs: Board profile generation and update

### ISSUE THREAD

**Issue by andrewleech** [renesas/micropython#2]
### Checks

- [X] I agree to follow the MicroPython [Code of Conduct](https://github.com/micropython/micropython/blob/master/CODEOFCONDUCT.md) to ensure a safe and respectful space for everyone.

- [X] I've searched for [existing issues](https://github.com/micropython/micropython/issues) and didn't find any that matched.

### Description

Hello,
I'm trying to work with the renesas-ra port in the official micropython repository. I'll preface this by saying I've never used renesas-ra parts or your software tooling before, howver I'm a regular micropython contributor working with many other ports and embedded parts.

I've got a EK_RA4W1 board and want to wire up a USB socket to use the mcu usb peripheral. I was _very_ dissaponted to find the usb header on the board has an ftdi chip attached for some reason rather than using the peripheral on the actual target chip, but that's a separate issue.

I've found I can't just enable USB in the standard micropython confuguration as there are missing settings / definitions in some headers in the ra_gen folder for that board?

From my initial reading, I'm guessing these files are generated by your gui fsp smart configurator program? 
Is there any way to load these back into the tool to update the peripheral configuration?

Is there any documentation somewhere that describes how the renesas generated files for a micropython board folder should be created if I wanted to create a new board profile? I'm used to other ports where auto-generated files are never used or needed.

Thanks!

**Comment by andrewleech** [comment]
Would it be possible to just get `configuration.xml` files for the evk boards currently defined in micropython?

**Comment by TakeoTakahashi2020** [comment]
Thank you for your report and adding notes to renesas-ra/README.md in https://github.com/micropython/micropython/pull/15160.
The configuration.xml files have been shared and pulled requested in micropython#15171.

**Comment by andrewleech** [comment]
Thanks for your assistance and contributions!
